name: CICD to s3
on:
  push:
    branches:
      - "main"
      - "dev"
      - "yisus44/feature/cicd"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: publishtos3session
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy dist folder to s3
        run: aws s3 sync ./dist s3://carewatch-en-equipo --delete
